### ISSUE TITLE
Throws Error when invalid arguments are passed ex: `fastly -v`

### ISSUE THREAD

**Issue by byteshiva** [fastly/cli#499]
**Version**

Please paste the output of `fastly version` here.

```
Fastly CLI version 1.3.0 (0a365cb)
Built with go version go1.17.3 linux/amd64
```

**What happened**

throws an error when invalid arguments are passed

example: 
**fastly -v**

```
 fastly -v 

INFO: 
Compatibility and versioning information for the Fastly CLI is being updated in the background.  The updated data will be used next time you execute a fastly command.
			
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7af72e]

goroutine 1 [running]:
github.com/fastly/kingpin.(*CmdClause).fullCommand(0x0)
	/home/runner/go/pkg/mod/github.com/fastly/kingpin@v2.1.12-0.20191105091915-95d230a53780+incompatible/cmd.go:241 +0x2e
github.com/fastly/kingpin.(*CmdClause).FullCommand(0xc000032050)
	/home/runner/go/pkg/mod/github.com/fastly/kingpin@v2.1.12-0.20191105091915-95d230a53780+incompatible/cmd.go:237 +0x19
github.com/fastly/cli/pkg/app.processCommandInput({0xd76058, {0xc000032050, 0x1, 0x1}, {0x2, {{0xc000330060, 0x16}}, {{0xc000372000, 0x34}, {0xc00032c0e8, ...}, ...}, ...}, ...}, ...)
	/home/runner/work/cli/cli/pkg/app/usage.go:281 +0x4ba
github.com/fastly/cli/pkg/app.Run({0xd76058, {0xc000032050, 0x1, 0x1}, {0x2, {{0xc000330060, 0x16}}, {{0xc000372000, 0x34}, {0xc00032c0e8, ...}, ...}, ...}, ...})
	/home/runner/work/cli/cli/pkg/app/run.go:93 +0x912
main.main()
	/home/runner/work/cli/cli/cmd/fastly/main.go:150 +0x898
````

To replicate, follow the below steps:
```
docker run  -it rust /bin/bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
nvm install --lts 
source ~/.bashrc
wget https://github.com/fastly/cli/releases/download/v1.3.0/fastly_1.3.0_linux_amd64.deb
dpkg -i https://github.com/fastly/cli/releases/download/v1.3.0/fastly_1.3.0_linux_amd64.deb

cd /home
mkdir example && cd example
fastly compute init
...
```

**Comment by fgsch** [comment]
Confirmed.
