### ISSUE TITLE
SIGSEGV on fastly backend create (v1.7.0)

### ISSUE THREAD

**Issue by jfoote** [fastly/cli#540]
**Version**

```
% fastly version
Fastly CLI version 1.7.0 (6150a45)
Built with go version go1.17.7 linux/amd64
```

**What happened**

Hello. I got a SIGSEGV when attempting to run `fastly backend create`. See details below.

```
fastly backend create --version=latest --name=<REDACTED> --address=<REDACTED_IPV4_ADDRESS> --port=8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e52df]

goroutine 1 [running]:
github.com/fastly/kingpin.(*uintValue).Set(0xc000206528, {0x20671656d, 0x19acbc0})
	/home/runner/go/pkg/mod/github.com/fastly/kingpin@v2.1.12-0.20191105091915-95d230a53780+incompatible/values_generated.go:679 +0x3f
github.com/fastly/kingpin.(*Application).setValues(0xc0003c0ea0, 0xc0004cc160)
	/home/runner/go/pkg/mod/github.com/fastly/kingpin@v2.1.12-0.20191105091915-95d230a53780+incompatible/app.go:479 +0x354
github.com/fastly/kingpin.(*Application).Parse(0xc0003c0ea0, {0xc000030080, 0x19ac978, 0x4})
	/home/runner/go/pkg/mod/github.com/fastly/kingpin@v2.1.12-0.20191105091915-95d230a53780+incompatible/app.go:240 +0xd0
github.com/fastly/cli/pkg/app.processCommandInput({0x19f1b48, {0xc000030080, 0x6, 0x6}, {{{0xc00024a280, 0x34}, {0xc00020a298, 0x2}, {0xc0002221e0, 0x19}, ...}, ...}, ...}, ...)
	/home/runner/work/cli/cli/pkg/app/usage.go:319 +0x6b4
github.com/fastly/cli/pkg/app.Run({0x19f1b48, {0xc000030080, 0x6, 0x6}, {{{0xc00024a280, 0x34}, {0xc00020a298, 0x2}, {0xc0002221e0, 0x19}, ...}, ...}, ...})
	/home/runner/work/cli/cli/pkg/app/run.go:95 +0x952
main.main()
	/home/runner/work/cli/cli/cmd/fastly/main.go:183 +0xa58
```

OS details follow

```
% sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

**Comment by fgsch** [comment]
Confirmed. Can repro with `fastly backend create --address=1.2.3.4 --port=8080`.

**Comment by Integralist** [comment]
Thanks @jfoote for raising this issue, and thanks @fgsch for validating!

Yup it looks like the `--port` is the culprit. The moment I add that it explodes 😬 

I'll take a look into this soon.

**Comment by fgsch** [comment]
Same issue with `fastly healthcheck create --timeout=10`

**Comment by fgsch** [comment]
For completion, I believe it affects all these:

```
pkg/commands/healthcheck/create.go:	c.CmdClause.Flag("timeout", "Timeout in milliseconds").UintVar(c.Input.Timeout)
pkg/commands/healthcheck/create.go:	c.CmdClause.Flag("check-interval", "How often to run the healthcheck in milliseconds").UintVar(c.Input.CheckInterval)
pkg/commands/healthcheck/create.go:	c.CmdClause.Flag("expected-response", "The status code expected from the host").UintVar(c.Input.ExpectedResponse)
pkg/commands/healthcheck/create.go:	c.CmdClause.Flag("window", "The number of most recent healthcheck queries to keep for this healthcheck").UintVar(c.Input.Window)
pkg/commands/healthcheck/create.go:	c.CmdClause.Flag("threshold", "How many healthchecks must succeed to be considered healthy").UintVar(c.Input.Threshold)
pkg/commands/healthcheck/create.go:	c.CmdClause.Flag("initial", "When loading a config, the initial number of probes to be seen as OK").UintVar(c.Input.Initial)
pkg/commands/backend/create.go:	c.CmdClause.Flag("port", "Port number of the address").UintVar(c.Input.Port)
pkg/commands/backend/create.go:	c.CmdClause.Flag("connect-timeout", "How long to wait for a timeout in milliseconds").UintVar(c.Input.ConnectTimeout)
pkg/commands/backend/create.go:	c.CmdClause.Flag("max-conn", "Maximum number of connections").UintVar(c.Input.MaxConn)
pkg/commands/backend/create.go:	c.CmdClause.Flag("first-byte-timeout", "How long to wait for the first bytes in milliseconds").UintVar(c.Input.FirstByteTimeout)
pkg/commands/backend/create.go:	c.CmdClause.Flag("between-bytes-timeout", "How long to wait between bytes in milliseconds").UintVar(c.Input.BetweenBytesTimeout)
pkg/commands/backend/create.go:	c.CmdClause.Flag("weight", "Weight used to load balance this backend against others").UintVar(c.Input.Weight)
```

**Comment by Integralist** [comment]
Thanks @jfoote for raising this issue. I've fixed the problem in our `main` branch and will shortly cut a new patch release.

**Comment by jfoote** [comment]
Thanks!
