### ISSUE TITLE
fastly command fails when run with no arguments

### ISSUE THREAD

**Issue by mteodoro** [fastly/cli#691]
**Version**

```
Fastly CLI version v4.2.0 (a1e8772)
Built with go version go1.18.6 linux/amd64
Viceroy version: viceroy 0.3.1
```
**What happened**

Running `fastly` with no arguments panics:

```
$ fastly
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/fastly/cli/pkg/cmd.IsHelpFlagOnly(...)
        /home/runner/work/cli/cli/pkg/cmd/cmd.go:228
github.com/fastly/cli/pkg/app.processCommandInput({0x1ae1cf8, {0xc000030200, 0x0, 0x0}, {{{0xc000203d78, 0x5}}, 0x2, {{0xc00022e820, 0x16}}, {{{...}, ...}, ...}, ...}, ...}, ...)
        /home/runner/work/cli/cli/pkg/app/usage.go:249 +0x11a5
github.com/fastly/cli/pkg/app.Run({0x1ae1cf8, {0xc000030200, 0x0, 0x0}, {{{0xc000203d78, 0x5}}, 0x2, {{0xc00022e820, 0x16}}, {{{...}, ...}, ...}, ...}, ...})
        /home/runner/work/cli/cli/pkg/app/run.go:109 +0xf91
main.main()
        /home/runner/work/cli/cli/cmd/fastly/main.go:132 +0x758
```

**Comment by Integralist** [comment]
Hi @mteodoro this issue was fixed in https://github.com/fastly/cli/pull/683 but I've not cut a new CLI release yet (I'll be doing that soon). Thanks.
