### ISSUE TITLE
trying to empty a kv store caused a sigsegv

### ISSUE THREAD

**Issue by JakeChampion** [fastly/cli#999]
**Version**

```
❯ fastly version
Fastly CLI version v10.3.0 (ed0fad39)
Built with go version go1.20.7 linux/amd64
Viceroy version: viceroy 0.7.0
```

**What happened**
```
fastly kv-store-entry delete --all -s zb4tcayi4lqr4vipdk2zeg

WARNING: This will delete ALL entries from your store!

Are you sure you want to continue? [yes/no]: yes

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1027dfd98]

goroutine 1 [running]:
github.com/fastly/go-fastly/v8/fastly.(*ListKVStoreKeysPaginator).Next(0x140002b4690)
        /home/runner/go/pkg/mod/github.com/fastly/go-fastly/v8@v8.5.7/fastly/kv_store.go:301 +0xe8
github.com/fastly/cli/pkg/commands/kvstoreentry.(*DeleteCommand).deleteAllKeys(0x1400258a400, {0x102f4b578?, 0x1400000dcf8})
        /home/runner/work/cli/cli/pkg/commands/kvstoreentry/delete.go:135 +0x114
github.com/fastly/cli/pkg/commands/kvstoreentry.(*DeleteCommand).Exec(0x1400258a400, {0x102f4c2f8?, 0x1400000e010?}, {0x102f4b578, 0x1400000dcf8})
        /home/runner/work/cli/cli/pkg/commands/kvstoreentry/delete.go:86 +0x1b4
github.com/fastly/cli/pkg/app.Run({0x102f47e10, {0x140000301f0, 0x5, 0x5}, {{{0x14000243248, 0x6}}, 0x2, {{0x14000041ce0, 0x16}}, {{{...}, ...}, ...}, ...}, ...})
        /home/runner/work/cli/cli/pkg/app/run.go:184 +0x17d0
main.main()
        /home/runner/work/cli/cli/cmd/fastly/main.go:115 +0x8f4
```

**Comment by dgryski** [comment]
Oops.  This is my fault.  Pretty straight-forward to fix.

https://github.com/fastly/go-fastly/blob/main/fastly/kv_store.go#L301

On error, `o` is likely `nil` and that's exactly what happened here.

**Comment by dgryski** [comment]
https://github.com/fastly/go-fastly/pull/468
